<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc53df897e3552776d487006acd038c80
{
    public static $files = array (
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'chillerlan\\Settings\\' => 20,
            'chillerlan\\QRCode\\' => 18,
        ),
        'T' => 
        array (
            'Twig\\' => 5,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Ctype\\' => 23,
        ),
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'F' => 
        array (
            'FontLib\\' => 8,
        ),
        'D' => 
        array (
            'Dotenv\\' => 7,
            'Dompdf\\' => 7,
        ),
        'B' => 
        array (
            'Box\\Spout\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'chillerlan\\Settings\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-settings-container/src',
        ),
        'chillerlan\\QRCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-qrcode/src',
        ),
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'FontLib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phenx/php-font-lib/src/FontLib',
        ),
        'Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
        'Dompdf\\' => 
        array (
            0 => __DIR__ . '/..' . '/dompdf/dompdf/src',
        ),
        'Box\\Spout\\' => 
        array (
            0 => __DIR__ . '/..' . '/box/spout/src/Spout',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'S' => 
        array (
            'Svg\\' => 
            array (
                0 => __DIR__ . '/..' . '/phenx/php-svg-lib/src',
            ),
            'Sabberworm\\CSS' => 
            array (
                0 => __DIR__ . '/..' . '/sabberworm/php-css-parser/lib',
            ),
        ),
        'P' => 
        array (
            'PhpOption\\' => 
            array (
                0 => __DIR__ . '/..' . '/phpoption/phpoption/src',
            ),
        ),
        'O' => 
        array (
            'Openpay' => 
            array (
                0 => __DIR__ . '/..' . '/openpay/sdk',
            ),
        ),
    );

    public static $classMap = array (
        'Conekta\\Address' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Address.php',
        'Conekta\\ApiError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/ApiError.php',
        'Conekta\\AuthenticationError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/AuthenticationError.php',
        'Conekta\\Card' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Card.php',
        'Conekta\\Charge' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Charge.php',
        'Conekta\\Conekta' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Conekta.php',
        'Conekta\\ConektaList' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/ConektaList.php',
        'Conekta\\ConektaObject' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/ConektaObject.php',
        'Conekta\\ConektaResource' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/ConektaResource.php',
        'Conekta\\Customer' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Customer.php',
        'Conekta\\DiscountLine' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/DiscountLine.php',
        'Conekta\\Event' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Event.php',
        'Conekta\\Handler' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/Handler.php',
        'Conekta\\Lang' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Lang.php',
        'Conekta\\LineItem' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/LineItem.php',
        'Conekta\\Log' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Log.php',
        'Conekta\\MalformedRequestError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/MalformedRequestError.php',
        'Conekta\\Method' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Method.php',
        'Conekta\\NoConnectionError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/NoConnectionError.php',
        'Conekta\\Order' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Order.php',
        'Conekta\\ParameterValidationError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/ParameterValidationError.php',
        'Conekta\\Payee' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Payee.php',
        'Conekta\\PaymentMethod' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/PaymentMethod.php',
        'Conekta\\PaymentSource' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/PaymentSource.php',
        'Conekta\\Payout' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Payout.php',
        'Conekta\\PayoutMethod' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/PayoutMethod.php',
        'Conekta\\Plan' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Plan.php',
        'Conekta\\ProcessingError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/ProcessingError.php',
        'Conekta\\Requestor' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Requestor.php',
        'Conekta\\ResourceNotFoundError' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Exceptions/ResourceNotFoundError.php',
        'Conekta\\ShippingContact' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/ShippingContact.php',
        'Conekta\\ShippingLine' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/ShippingLine.php',
        'Conekta\\Subscription' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Subscription.php',
        'Conekta\\TaxLine' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/TaxLine.php',
        'Conekta\\Token' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Token.php',
        'Conekta\\Util' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Util.php',
        'Conekta\\Webhook' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/Webhook.php',
        'Conekta\\WebhookLog' => __DIR__ . '/..' . '/conekta/conekta-php/lib/Conekta/WebhookLog.php',
        'Cpdf' => __DIR__ . '/..' . '/dompdf/dompdf/lib/Cpdf.php',
        'HTML5_Data' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/Data.php',
        'HTML5_InputStream' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/InputStream.php',
        'HTML5_Parser' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/Parser.php',
        'HTML5_Tokenizer' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/Tokenizer.php',
        'HTML5_TreeBuilder' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/TreeBuilder.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc53df897e3552776d487006acd038c80::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc53df897e3552776d487006acd038c80::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitc53df897e3552776d487006acd038c80::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitc53df897e3552776d487006acd038c80::$classMap;

        }, null, ClassLoader::class);
    }
}
